name: Scheduled Task (Market Data)

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Market Script
        run: |
          echo "Running scheduled task"
          python market.py
