name: Scheduled Task (Market Data)

on:
  schedule:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Market Script
        run: |
          echo "Running scheduled task"
          python market.py

