name: Scheduled Task (Market Data)

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
    workflow_dispatch:
jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Replace '3.x' with the specific Python version you use, e.g., '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scrapy beautifulsoup4

      - name: Run Market Script
        run: |
          echo "Running scheduled task"
          python market.py
